#include "../../include/IO/TextFileParser.h"
#include "../../include/Lattices/LatticeModule.h"
#include <numbers>

/* This example demonstrates the construction of a mixed tilt-twist grain
 * boundary in a 3D bicrystal, and the atomistic box construction for it. The
 * following is a snippet from the output generated by testGenerateGBs. In
 * this example, we construct a Sigma 7 mixed GB about the [111] axis.
Lattice A =
  0 0.5 0.5
0.5   0 0.5
0.5 0.5   0
Cartesian coordinates of axis =
1 1 1
###################################################
Misorientation angle = 38.213210701738198338; Sigma = 7
Mixed GBs for this misorientation
1) [Mixed] nA = -1 1 3
         nB =  9.0000000000000017764 -17 -12.999999999999998224
         CSL plane distance (Height) = 0.30151134457776312958
*/

using namespace oILAB;
int main() {
  const int dim = 3;
  /*! [lattice1] */
  Eigen::Matrix3d A;
  A << 0.0, 0.5, 0.5, 0.5, 0.0, 0.5, 0.5, 0.5, 0.0;
  Lattice<dim> L1(A);
  /*! [lattice1] */

  /*! [axis] */
  Eigen::Vector3d axis;
  axis << 1, 1, 1;
  ReciprocalLatticeVector<dim> rv(
      L1.reciprocalLatticeDirection(axis).reciprocalLatticeVector());
  /*! [axis] */

  /*! [lattice2] */
  double angle = 38.213210701738198338 * std::numbers::pi / 180;
  Eigen::AngleAxisd rotation(angle, axis.normalized());
  Lattice<dim> L2(A, rotation.matrix());
  /*! [lattice2] */

  try {
    /*! [bicrystal] */
    BiCrystal<dim> bc(L1, L2);
    std::cout << "Sigma = " << bc.sigma << std::endl;
    /*! [bicrystal] */

    /*! [gb] */
    // A mixed boundary's normal is neither in-plane with, nor parallel to,
    // the misorientation axis.
    ReciprocalLatticeVector<dim> normal(L1);
    normal << -1, 1, 3;
    Gb<dim> gb(bc, normal);
    /*! [gb] */
    std::cout << "Miller indices w.r.t A: ";
    std::cout << gb.nA << std::endl;
    std::cout << "Miller indices w.r.t B: ";
    std::cout << gb.nB << std::endl;

    /*! [in-plane vectors] */
    // Two CSL vectors spanning the GB plane exactly (both orthogonal to the
    // normal by construction; RLLL-reduced by planeParallelLatticeBasis to be
    // short, but only approximately orthogonal to *each other*).
    auto planeParallelBasis = bc.csl.planeParallelLatticeBasis(
        gb.bc.getReciprocalLatticeDirectionInC(gb.nA.reciprocalLatticeVector()),
        true);
    LatticeVector<dim> inPlane1(planeParallelBasis[1].latticeVector());
    LatticeVector<dim> inPlane2(planeParallelBasis[2].latticeVector());
    /*! [in-plane vectors] */

    /*! [axis vector] */
    // No exact shortcut is available for the transverse vector here (the
    // axis is neither in-plane nor along the normal for a mixed boundary),
    // but the CSL vector along the axis is still a reasonable initial guess,
    // refined below via updateBoxVectors.
    LatticeVector<dim> vectorAlongAxisA(
        bc.A.latticeDirection(rv.cartesian()).latticeVector());
    LatticeVector<dim> vectorAlongAxisC(
        bc.getLatticeDirectionInC(vectorAlongAxisA).latticeVector());
    /*! [axis vector] */

    /*! [box vectors] */
    // inPlane1/inPlane2 (the true in-plane pair) stay fixed in slots [1]/[2],
    // so updateBoxVectors' internal reference (inPlane1 x inPlane2) is
    // exactly proportional to the true GB normal - this call only ever
    // refines slot [0] (vectorAlongAxisC), never touching the
    // guaranteed-in-plane pair, so the result is always commensurate with
    // the GB plane regardless of how well vectorAlongAxisC starts out.
    std::vector<LatticeVector<dim>> boxVectors{vectorAlongAxisC, inPlane1,
                                                inPlane2};
    gb.bc.updateBoxVectors(boxVectors, 0.8);

    std::cout << "Input box vectors = " << std::endl;
    std::cout << boxVectors[0].cartesian().transpose() << std::endl;
    std::cout << boxVectors[1].cartesian().transpose() << std::endl;
    std::cout << boxVectors[2].cartesian().transpose() << std::endl;

    Eigen::Matrix<long long int, dim, dim> boxVectorsIntegerCoords;
    for (int i = 0; i < dim; ++i)
      boxVectorsIntegerCoords.col(i) = boxVectors[i];
    std::cout << "Estimated number of atoms in the GB: "
              << 2 * abs(bc.sigma * boxVectorsIntegerCoords.template cast<double>()
                                        .determinant())
              << std::endl;

    gb.box(boxVectors, 0, "gbMixed.txt", true);
    /*! [box vectors] */

  } catch (std::runtime_error &e) {
    std::cout << e.what() << std::endl;
    return -1;
  }
  return 0;
}
