#include "../../include/IO/TextFileParser.h"
#include "../../include/Lattices/LatticeModule.h"
#include <numbers>

/* This example demonstrates the construction of a twist grain boundary in a 3D
 * bicrystal, and the atomistic box construction for it. The following is a
 * snippet from the output generated by testGenerateGBs. In this example, we
 * construct the [111] twist Sigma 7 GB.
Lattice A =
  0 0.5 0.5
0.5   0 0.5
0.5 0.5   0
Cartesian coordinates of axis =
1 1 1
###################################################
Misorientation angle = 38.213210701738198338; Sigma = 7
Twist GB for this misorientation
1) [Twist] nA = 1 1 1
         nB = -1 -1 -1
         CSL plane distance (Height) = 0.57735026918962661924
*/

using namespace oILAB;
int main() {
  const int dim = 3;
  /*! [lattice1] */
  Eigen::Matrix3d A;
  A << 0.0, 0.5, 0.5, 0.5, 0.0, 0.5, 0.5, 0.5, 0.0;
  Lattice<dim> L1(A);
  /*! [lattice1] */

  /*! [axis] */
  Eigen::Vector3d axis;
  axis << 1, 1, 1;
  ReciprocalLatticeVector<dim> rv(
      L1.reciprocalLatticeDirection(axis).reciprocalLatticeVector());
  /*! [axis] */

  /*! [lattice2] */
  double angle = 38.213210701738198338 * std::numbers::pi / 180;
  Eigen::AngleAxisd rotation(angle, axis.normalized());
  Lattice<dim> L2(A, rotation.matrix());
  /*! [lattice2] */

  try {
    /*! [bicrystal] */
    BiCrystal<dim> bc(L1, L2);
    std::cout << "Sigma = " << bc.sigma << std::endl;
    /*! [bicrystal] */

    /*! [gb] */
    // A twist boundary's normal is exactly the misorientation axis.
    ReciprocalLatticeVector<dim> normal(L1);
    normal << 1, 1, 1;
    Gb<dim> gb(bc, normal);
    /*! [gb] */
    std::cout << "Miller indices w.r.t A: ";
    std::cout << gb.nA << std::endl;
    std::cout << "Miller indices w.r.t B: ";
    std::cout << gb.nB << std::endl;

    /*! [in-plane vectors] */
    // Two CSL vectors spanning the GB plane exactly (both orthogonal to the
    // normal by construction; RLLL-reduced by planeParallelLatticeBasis to be
    // short, but only approximately orthogonal to *each other*).
    auto planeParallelBasis = bc.csl.planeParallelLatticeBasis(
        gb.bc.getReciprocalLatticeDirectionInC(gb.nA.reciprocalLatticeVector()),
        true);
    LatticeVector<dim> inPlane1(planeParallelBasis[1].latticeVector());
    LatticeVector<dim> inPlane2(planeParallelBasis[2].latticeVector());
    /*! [in-plane vectors] */

    /*! [axis vector] */
    // The CSL vector along the misorientation axis: exactly transverse to the
    // GB plane for a twist boundary, since axis == normal by definition -
    // unlike planeParallelLatticeBasis[0], which only satisfies a duality
    // condition (dot product 1 with the normal) and is not guaranteed to be
    // exactly parallel to it.
    LatticeVector<dim> vectorAlongAxisA(
        bc.A.latticeDirection(rv.cartesian()).latticeVector());
    LatticeVector<dim> vectorAlongAxisC(
        bc.getLatticeDirectionInC(vectorAlongAxisA).latticeVector());
    /*! [axis vector] */

    /*! [box vectors] */
    // vectorAlongAxisC is already exactly orthogonal to the GB plane spanned
    // by {inPlane1, inPlane2} (axis == normal, by definition of a twist
    // boundary), so unlike the tilt/mixed cases there is nothing to refine
    // *about slot [0]* - but updateBoxVectors also orthogonalizes slot [1]
    // (inPlane1) against the fixed slot [2] (inPlane2), which is just as
    // relevant here as it is for tilt/mixed, and safe to call regardless
    // since it only ever writes to slots [0] and [1] while staying exactly
    // in-plane.
    std::vector<LatticeVector<dim>> boxVectors{vectorAlongAxisC, inPlane1,
                                                inPlane2};
    gb.bc.updateBoxVectors(boxVectors, 1.0);

    std::cout << "Input box vectors = " << std::endl;
    std::cout << boxVectors[0].cartesian().transpose() << std::endl;
    std::cout << boxVectors[1].cartesian().transpose() << std::endl;
    std::cout << boxVectors[2].cartesian().transpose() << std::endl;

    Eigen::Matrix<long long int, dim, dim> boxVectorsIntegerCoords;
    for (int i = 0; i < dim; ++i)
      boxVectorsIntegerCoords.col(i) = boxVectors[i];
    std::cout << "Estimated number of atoms in the GB: "
              << 2 * abs(bc.sigma * boxVectorsIntegerCoords.template cast<double>()
                                        .determinant())
              << std::endl;

    gb.box(boxVectors, 0, "gbTwist.txt", true);
    /*! [box vectors] */

  } catch (std::runtime_error &e) {
    std::cout << e.what() << std::endl;
    return -1;
  }
  return 0;
}
